var w = {
	hello : {"ar":"سلام","ku":"سلاو","en":"Helloww"},
	bye : {"ar":"مع الخیر","ku":"خواحافیز","en":"Bye"},
	dashboard : {ar:'',ku:'داشبۆرد',en:'Dashboard'},
	Dashboard : {ar:'',ku:'داشبۆرد',en:'Dashboard'},
	home : {ar:'اول',ku:'سەرەکی',en:'Home'},

	ControlPanel : {"ar":"","ku":"پانێلی کۆنترۆل","en":"Control Panel"},
	id : {"ar":"","ku":"#","en":"ID"},
	perm : {"ar":"","ku":"ئیجازەکان","en":"permission"},
	name : {"ar":"","ku":"ناو","en":"name"},
	username : {"ar":"","ku":"یوزەرنەیم","en":"username"},
	action : {"ar":"","ku":"چالاکی","en":"action"},
	userTable : {"ar":"","ku":"خشتەی یوزەرەکان","en":"User Table"},
	addNew : {"ar":"","ku":"زیاد کردن","en":"Add New"},
	user : {"ar":"","ku":"بەکارهێنەر","en":"user"},
	password : {"ar":"","ku":"وشەی نهێنی","en":"password"},
	close : {"ar":"","ku":"بەستن","en":"close"},
	save : {"ar":"","ku":"سەیڤ کردن","en":"save"},
	editUser : {"ar":"","ku":"گۆرانکاری یوزەر","en":"Edit User"},
	edit : {"ar":"","ku":"گۆرانکاری","en":"Edit"},
	delete : {"ar":"","ku":"سرینەوە","en":"Delete"},
	addUser : {"ar":"","ku":"زیاد کردنی یوزەر","en":"Add User"},
	deleteUser : {"ar":"","ku":"متمانەت هەیە لە سرینەوەی ئەم یوزەرە","en":"Are you sure to Delete this User"},
	employee : {"ar":"","ku":"فەرمانبەر","en":"Employee"},
	pleaseSignIn : {"ar":"","ku":"تکایە داخل بن","en":"Please Login"},
	signIn : {"ar":"","ku":"داخل بوون","en":"Login"},
	Logout : {"ar":"","ku":"دەرچون","en":"Logout"},
	MAIN_NAVIGATION : {"ar":"","ku":"لیستی سەرەکی","en":"MAIN NAVIGATION"},
	report : {"ar":"","ku":"راپۆرت","en":"Report"},
	employeeTable : {"ar":"","ku":"خشتەی کارمەندان","en":"Employee Table"},
	reportTable : {"ar":"","ku":"خشتەی راپۆرت","en":"Report Table"},
	department : {"ar":"","ku":"بەش","en":"Department"},
	Department : {"ar":"","ku":"بەش","en":"Department"},
	Date_Time : {"ar":"","ku":"بەروار/ساعەت","en":"Date/Time"},
	VerifyCode : {"ar":"","ku":"جۆری ناسین","en":"Verify Code"},
	inOut : {"ar":"","ku":"هاتن/رۆشتن","en":"in/Out"},
	DeviceID : {"ar":"","ku":"ئایدی جیهاز","en":"Device ID"},
	employeename : {"ar":"","ku":"ناوی","en":"Name"},
	/*--------------------new*/
	
	Setting: {"ar":"","ku":"سێتینگ","en":"Setting"},
	Backup: {"ar":"","ku":"بەکئۆپ","en":"Backup"},
	detail : {"ar":"","ku":"تێبینی","en":"Detail"},
	Count : {"ar":"","ku":"ژمارە","en":"Count"},
	All : {"ar":"","ku":"هەموو","en":"All"},
	Not_Unique : {"ar":"","ku":"ئەو ناوە دووبارەیە","en":"Not Unique"},
	Invalid_Mobile : {"ar":"","ku":"ژمارەی مۆبایل هەلەیە","en":"Invalid Mobile"},
	Invalid_Phone : {"ar":"","ku":"ژمارەی تەلەفون هەلەیە","en":"Invalid Phone"},
	Number_Of_Charachter_Is_More_Than_200 : {"ar":"","ku":"نابێ ژمارەی پیتەکان لە 200 زیاتر بێت","en":"Number Of Charachter Is More Than 200"},
	Name_Not_Walid : {"ar":"","ku":"ئەو ناوە ڕێگەپێنەدراوە","en":"Name Not Walid"},
	Delete_Not_Available : {"ar":"","ku":"ناتوانی بیسرێوە","en":"Delete Not Available"},
	edit_department : {"ar":"","ku":"گۆرینی بەش","en":"Edit Department"},
	add_department : {"ar":"","ku":"زیاد کردنی بەش","en":"Add Department"},
	delete_department : {"ar":"","ku":"سرینەوەی بەش","en":"Delete Department"},
	departmentTable : {"ar":"","ku":"خشتەی بەشەکان","en":"Department Table"},
	Not_In_Range : {"ar":"","ku":"لە مەودای دابین کراو دا نێت","en":"Not In Range"},
	Not_Be_Empty : {"ar":"","ku":"نابێت بەتال بێت","en":"Not Be Empty"},
	capacity : {"ar":"","ku":"فراوانی","en":"Capacity "},
	permission : {"ar":"","ku":"ئیجازەکان","en":"Permission"},
	Not_Perm_Pattern : {"ar":"","ku":"شێوازی داخلکردنی ئیجازە هەلەیە","en":"Not Perm Pattern"},
	Not_Valid_Email : {"ar":"","ku":"ئیمەیل هەلەیە","en":"Not Valid Email"},
	force_change_password : {"ar":"","ku":"زەخت بۆ گۆرینی وشەی نهێنی","en":"Force tp change password"},
	mobile : {"ar":"","ku":"مۆبایل","en":"Mobile"},
	email : {"ar":"","ku":"ئیمەیل","en":"Email"},
	add_user : {"ar":"","ku":"زیاد کردنی بەکارهێنەر","en":"Add user"},
	No : {"ar":"","ku":"نەخێر","en":"No"},
	Yes : {"ar":"","ku":"بەلێ","en":"Yes"},
	edit_user : {"ar":"","ku":"گۆرانکاری بۆ بەکارهێنەر","en":"Edit User"},
	If_you_would_not_change_remain_it_empty : {"ar":"","ku":"گەر ناتهەوێ بیگۆری بەتال بیهێلەوە","en":"(If you would not change remain it empty)"},
	force : {"ar":"","ku":"زەخت","en":"Force"},
	delete_user : {"ar":"","ku":"سرینەوەی بەکارهێنەر","en":"Delete User"},
	Username_Not_Exist : {"ar":"","ku":"ئەم یوەرنەیمە بوونی نێت","en":"Username Not Exist"},
	Incorrect_Password : {"ar":"","ku":"وشەی نهێنی هەلەیە","en":"Incorrect Password"},
	language : {"ar":"","ku":"زمان","en":"Language"},
	Nothing_to_export : {"ar":"","ku":"هیچ نێت بۆ دانلۆد کردن","en":"Nothing to export"},
	highschoolTable : {"ar":"","ku":"خشتەی قوتابخانە","en":"Highschool Table"},
	code : {"ar":"","ku":"کۆد","en":"Code"},
	You_Havent_Permission_To_Add : {"ar":"","ku":"ئیجازەت نێت بۆ داخل کردن","en":"You Haven't Permission To Add"},
	You_Havent_Permission_To_Edit : {"ar":"","ku":"ئیجازەت نێت بۆ گۆرانکاری","en":"You Haven't Permission To Edit"},
	You_Havent_Permission_To_Delete : {"ar":"","ku":"ئیجازەت نێت بۆ سرینەوە","en":"You Haven't Permission To Delete"},
	ratio : {"ar":"","ku":"راژە","en":"Ratio"},
	resetAll : {"ar":"","ku":"رێسێت کردن","en":"Reset All"},
	nameKurdish : {"ar":"","ku":"ناو بە کوردی","en":"Name Kurdish"},
	nameEnglish : {"ar":"","ku":"ناو بە ئینگلیزی","en":"Name English"},
	state : {"ar":"","ku":"حالەتی","en":"State"},
	type : {"ar":"","ku":"جۆر","en":"Type"},
	stateBirth : {"ar":"","ku":"لە دایکبووی","en":"State Birth"},
	birthPlace : {"ar":"","ku":"شۆنی لە دایک بوون","en":"Birth Place"},
	gender : {"ar":"","ku":"رەگەز","en":"Gender"},
	dob : {"ar":"","ku":"بەرواری لە دایک بوون","en":"Date Of Birth"},
	homePhone : {"ar":"","ku":"تەلەفونی مال","en":"Home Phone"},
	city : {"ar":"","ku":"شار","en":"City"},
	quarter: {"ar":"","ku":"گەرەک","en":"Quarter"},
	quarterNumber : {"ar":"","ku":"ژمارەی گەرەک","en":"Quarter Number"},
	homeNumber : {"ar":"","ku":"ژمارەی خانوو","en":"Home Number"},
	valeyNumber : {"ar":"","ku":"ژمارەی کۆلان","en":"Valey Number"},
	at_least_select_one : {"ar":"","ku":"بەلايەنى كەم دەبێت یەکدانە هەلبژێری","en":"at least select one"},
	branch : {"ar":"","ku":"لق","en":"Branch"},
	depp : {"ar":"","ku":"بەش","en":"Department"},
	Main : {"ar":"","ku":"سەرەکی","en":"Main"},
	cat : {"ar":"","ku":"جۆر","en":"Category"},
	brand : {"ar":"","ku":"برەند","en":"Brand"},
	product : {"ar":"","ku":"بەرهەم","en":"Product"},
	productTable : {"ar":"","ku":"خشتەی بەرهەمەکان","en":"Product Table"},
	price : {"ar":"","ku":"نرخ","en":"Price"},
	add_product : {"ar":"","ku":"زیاد کردنی بەرهەم","en":"Add Product"},
	ProductControl : {"ar":"","ku":"کۆنترۆلی بەرهەمەکان","en":"Products Control"},
	Invalid_Card : {"ar":"","ku":"کارت هەلەیە","en":"Invalid Card"},
	This_card_used_before : {"ar":"","ku":"ئەم کارتە پێشتر بەکار هاتۆ","en":"This card used before"},
	The_operation_to_add_card_successfully_done : {"ar":"","ku":"کارت بە سەرکەوتوویی داخل کرا","en":"The operation to add card successfully done"},
	Card_Number : {"ar":"","ku":"ژمارەی کارت","en":"Card Number"},
	card_number : {"ar":"","ku":"ژمارەی کارت","en":"Card Number"},
	idAccount : {"ar":"","ku":"ئایدی ئەکاونت","en":"ID Account"},
	This_account_not_exist : {"ar":"","ku":"ئەو ئەکاونتە بوونی نێت","en":"This account not exist"},
	The_operation_to_add_transaction_successfully_done : {"ar":"","ku":"کرێدیت بە سەرکەوتوویی داخل کرا","en":"The operation to add transaction successfully done"},
	Invalid_Credit : {"ar":"","ku":"کرێدیتەکە هەلەیە","en":"Invalid Credit"},
	This_account_have_not_any_card : {"ar":"","ku":"ئەم ئەکاونتە کارتی نێت","en":"This account have not any card"},
	Invalid_credit : {"ar":"","ku":"کرێدیت هەلەیە","en":"Invalid Credit"},
	This_credit_used_before : {"ar":"","ku":"ئەو کرێدیتە پێشتر بەکار هاتۆ","en":"This credit used before"},
	credit : {"ar":"","ku":"کرێدیت","en":"Credit"},
	Please_enter_your_card_number : {"ar":"","ku":"تکایە ژمارەی سەر کارت داخل بکە","en":"Please enter your card number"},
	if_you_have_problem_please_read_manual : {"ar":"","ku":"گەر پێویستیت بە یارمەتیە لێرە کلیک بکە","en":"If you have problem please read manual"},
	You_must_enter_the_12_digit_on_your_service_cart : {"ar":"","ku":"دەبێ 12 ژمارەی سەر کارتی تایبەت بە کریار داخل کەن","en":"You must enter the 12 digit on your service cart"},
	Be_aware_you_dont_enter_the_number_of_credit_card_to_this_part : {"ar":"","ku":"ئاگادار بن بە هەلە ژمارەی کارتی کرێدیت داخل نەکەن","en":"Be aware you dont enter the number of credit card to this part"},
	If_you_have_any_question_please_call : {"ar":"","ku":"گەر کێشەکەتان بۆ حەل نەبوو، پەیوەندی بکەن بەم ژمارە مۆبایلە","en":"If you have any question please call"},
	No_need_to_insert_dash : {"ar":"","ku":"پێویست ناکات هێلی لێدان (-) داخل کەی","en":"No need to insert dash (-)"},
	If_you_insert_more_than_10_time_mistake_informtion_will_be_block_for_5_hour : {"ar":"","ku":"گەر زیاتر لە 10 جار زانیارێکانت بە هەلە داخل کەی، بۆ ماوەی 5 ساعەت بەن دەکرێی","en":"If you insert more than 10 time mistake informtion will be block for 5 hour"},
	This_time_enter_your_password : {"ar":"","ku":"ئەوجار پەسوۆردەکەت داخل کە","en":"This time enter your password"},
	If_this_is_first_time_ener_password_enter_the_password_that_HI_company_give_to_you : {"ar":"","ku":"ئەگەر یەکەم جارتە پەسوۆرد داخل دەکەی، ئەم پەسوۆردە داخل کە، کە لە لایەن کۆمپانیای های بە تۆ دراوە.","en":"If this is first time ener password enter the password that HI company give to you"},
	Wrong_Password : {"ar":"","ku":"پەسوۆرد هەلەیە","en":"Wrong Password"},
	phone : {"ar":"","ku":"تەلەفوون","en":"Phone"},
	serial : {"ar":"","ku":"سریال","en":"Serial"},
	dateAdded : {"ar":"","ku":"بەرواری هاتن","en":"Date Added"},
	ID_User : {"ar":"","ku":"ئایدی یوزەر","en":"ID User"},
	dinar : {"ar":"","ku":"درهم","en":"Dinar"},
	Profile : {"ar":"","ku":"پرۆفایل","en":"Profile"},
	Add_Credit : {"ar":"","ku":"زیاد کردنی کرێدیت","en":"Add Credit"},
	Credit : {"ar":"","ku":"کرێدیت","en":"Credit"},
	Transaction : {"ar":"","ku":"مامەڵە","en":"Transaction"},
	dinar_box : {"ar":"","ku":"ماوە - درهم","en":"Dinar Box"},
	Dear : {"ar":"","ku":"بەرێز","en":"Dear"},
	Welcome_to_Hi_Portal : {"ar":"","ku":"بەخێر بێیت بۆ پۆرتالی های","en":"Welcome to Hi-Portal"},
	Customer_Information : {"ar":"","ku":"زانیارێکانی خاوەن ئەکاونت","en":"Customer Information"},
	piece : {"ar":"","ku":"قەتعەکان","en":"Pieces"},
	Accounting : {"ar":"","ku":"ژمێریاری","en":"Accounting"},
	account : {"ar":"","ku":"حیساب","en":"account"},
	Payin : {"ar":"","ku":"پارە وەرگرتن","en":"Payin"},
	Payout : {"ar":"","ku":"پارە دان","en":"Payout"},
	DollarRate : {"ar":"","ku":"نرخی دۆلار","en":"DollarRate"},
	Pieces : {"ar":"","ku":"قەتعەکان","en":"Pieces"},
	inDepp : {"ar":"","ku":"پسولەی کرین","en":"Buy Invoice"},
	user_depp : {"ar":"","ku":"بەش بۆ بەکارهێنەر","en":"Department for User"},
	depp_cat : {"ar":"","ku":"بەش بۆ جۆری بەرهەم","en":"Department for Category"},
	model : {"ar":"","ku":"مۆدێل","en":"Model"},
	store : {"ar":"","ku":"گەنجینە","en":"Store"},
	Bank : {"ar":"","ku":"بانک","en":"Bank"},
	Card : {"ar":"","ku":"کارت","en":"Card"},
	indepp_piece_new : {"ar":"","ku":"پسولەی کرینی قەتعەکانی مۆبایل","en":"Buy New Pieces"},
	invoice : {"ar":"","ku":"پسوولە","en":"Invoice"},
	accountType : {"ar":"","ku":"جۆری حیساب","en":"Account Type"},
	userDeppAuth : {"ar":"","ku":"بەش","en":"Department"},
	Code : {"ar":"","ku":"کۆد","en":"Code"},
	Brand : {"ar":"","ku":"برەند","en":"Brand"},
	Model : {"ar":"","ku":"مۆدێل","en":"Model"},
	Product : {"ar":"","ku":"بەرهەم","en":"Product"},
	description : {"ar":"","ku":"شەرح","en":"Description"},
	Cost : {"ar":"","ku":"نرخ","en":"Cost"},
	Qty : {"ar":"","ku":"عەدەد","en":"Qty"},
	SubTotal : {"ar":"","ku":"کۆی گشتی","en":"Sub Total"},
	Discount : {"ar":"","ku":"داشکاندن","en":"Discount"},
	Rate: {"ar":"","ku":"راژە","en":"Rate"},
	isEqualTo  : {"ar":"","ku":"بەرامبەرە بە","en":"Is Equal To"},
	GrandTotal : {"ar":"","ku":"کۆی گشتی دوای داشکاندن","en":"Grand Total"},
	Detail : {"ar":"","ku":"تێبینی","en":"Detail"},
	Pay : {"ar":"","ku":"دان","en":"Pay"},
	lessFromAccount : {"ar":"","ku":"کەمی کەوە لە حیسابی","en":"Less From Account"},
	Save : {"ar":"","ku":"سەیڤ","en":"Save"},
	cash : {"ar":"","ku":"سندوق","en":"Cash"},
	indepp_pieceTable : {"ar":"","ku":"خشتەی داخل کردنی قەتعە","en":"Buy Invoice List for Pieces"},
	dollar : {"ar":"","ku":"دۆلار","en":"dollar"},
	date : {"ar":"","ku":"بەروار","en":"date"},
	dollar_rate : {"ar":"","ku":"نرخی دۆلار","en":"Dollar Price"},
	addToCash : {"ar":"","ku":"زیاد کردن بۆ سندوق","en":"Add To Cash"},
	address : {"ar":"","ku":"ناونیشان","en":"Address"},
	card : {"ar":"","ku":"کارت","en":"Card"},
	accountTable : {"ar":"","ku":"خشتەی حیساب","en":"Account Table"},
	deppTable : {"ar":"","ku":"","en":"deppTable"},
	Cash : {"ar":"","ku":"نەقد","en":"Cash"},
	Piece_mobile : {"ar":"","ku":"قەتعەکانی مۆبایل","en":"Mobile Pieces"},
	Repair_mobile : {"ar":"","ku":"چاککردنەوەی مۆبایل","en":"Repair Mobile"},
	Repair_computer : {"ar":"","ku":"چاککردنەوەی کۆمپییوتەر","en":"Repair Computer"},
	Mobile : {"ar":"","ku":"مۆبایل","en":"Mobile"},
	Camera : {"ar":"","ku":"کامێرا","en":"Camera"},
	Software : {"ar":"","ku":"سۆفتوێر","en":"Software"},
	Laptop : {"ar":"","ku":"لەپتۆپ","en":"Laptop"},
	Accessories : {"ar":"","ku":"ئیکسیسوارات","en":"Accessories"},
	camera : {"ar":"","ku":"کامێرا","en":"Camera"},
	Product_must_be_selected : {"ar":"","ku":"بەرهەم دەبێت هەلبژێردرێت","en":"Product must be selected"},
	Date : {"ar":"","ku":"بەروار","en":"Date"},
	active : {"ar":"","ku":"چاڵاک","en":"Active"},
	status : {"ar":"","ku":"حالەت","en":"Status"},
	done : {"ar":"","ku":"حیساب تەواو","en":"Done"},
	progress : {"ar":"","ku":"پارەی ماوە","en":"Progress"},
	totalOfInvoice : {"ar":"","ku":"کۆی گشتی پسولە","en":"Total Of Invoice"},
	totaPayout : {"ar":"","ku":"کۆی گشتی پارەی پێ دراو","en":"Tota Payout"},
	Remained : {"ar":"","ku":"باقی","en":"Remained"},
	Must_Fill_Dollar_or_Dinar : {"ar":"","ku":"دەبێت دۆلار یان دینار داخل کەی","en":"Must Fill Dollar Or Dinar"},
	less_from_account : {"ar":"","ku":"کەمی کەوە لە حیسابی","en":"Less from account"},
	Buyer : {"ar":"","ku":"کریار","en":"Buyer"},
	Seller : {"ar":"","ku":"فرۆشیار","en":"Seller"},
	TotalInDinar : {"ar":"","ku":"کۆ بە دینار","en":"Total In Dinar"},
	Total : {"ar":"","ku":"کۆ","en":"Total"},
	Payment_Info_Table : {"ar":"","ku":"خشتەی پارە دان","en":"Payment Info Table"},
	InDollar : {"ar":"","ku":"بە دۆڵار","en":"In Dollar"},
	Account : {"ar":"","ku":"حیساب","en":"Account"},
	ID : {"ar":"","ku":"ئایدی","en":"ID"},
	SellerSign : {"ar":"","ku":"واژووی فرۆشیار","en":"Seller Sign"},
	AccounterSign : {"ar":"","ku":"واژووی ژمێریار","en":"AccounterSign"},
	indepp_piece_edit : {"ar":"","ku":"گۆرانکاری لە پسولەی قەتعەکانی مۆبایل","en":"Indepp Piece Edit"},
	You_Cant_Edit_Different_Date : {"ar":"","ku":"تۆ ناتوانی بەرواری جیاواز بسرێوە","en":"You Cant Edit Different Date"},
	outDepp : {"ar":"","ku":"پسولەی فرۆش","en":"Sell Invoice"},
	outdepp_piece_new : {"ar":"","ku":"پسولەی فرۆش قەتعەی موبایل","en":"Piece Sell Invoice"},
	accountInDepp : {"ar":"","ku":"حساب لە بەش","en":"Account In Depp"},
	repair_mobile : {"ar":"","ku":"چاک کردنەوەی مۆبایل","en":"Repair Mobile"},
	add : {"ar":"","ku":"زیاد کردن","en":"Add"},
	mobileRepairman : {"ar":"","ku":"وەستای مۆبایل","en":"Mobile Repairman"},
	Order_New_Mobile_Repair : {"ar":"","ku":"فۆرمی چاک کردنەوەی مۆبایل","en":"Order New Mobile Repair"},
	NewCustomer : {"ar":"","ku":"کریاری نوێ","en":"New Customer"},
	totalPayin : {"ar":"","ku":"کۆی گشتی پارەی وەرگیراو","en":"Total Payin"},
	addToAccount : {"ar":"","ku":"بیخەرە سەر حیسابی","en":"Add To Account"},
	Payin_Info_Table : {"ar":"","ku":"خشتەی پارە وەرگرتن","en":"Payin Info Table"},
	buyerSign : {"ar":"","ku":"واژووی کڕیار","en":"Buyer Sign"},
	repairList : {"ar":"","ku":"لیستی چاک کردنەوە","en":"Repair List"},
	mobileRepairInvoice : {"ar":"","ku":"چاک کردنەوەی مۆبایل","en":"Mobile Repair Invoice"},
	date_back : {"ar":"","ku":"بەرواری گەرانەوە","en":"Date Back"},
	invoiceNumber : {"ar":"","ku":"ژمارە پسولە","en":"Invoice Number"},
	Problems : {"ar":"","ku":"کێشەکان","en":"Problems"},
	Guaranty : {"ar":"","ku":"گەرەنتی","en":"Guaranty"},
	Repairman : {"ar":"","ku":"چاک کەرەوە","en":"Repairman"},
	balanceTotal : {"ar":"","ku":"بالانسی گشتی","en":"BalanceTotal"},
	in_dollar : {"ar":"","ku":"بە دۆللار","en":"inDollar"},
	in_out : {"ar":"","ku":"ز/ک","en":"In/Out"},
	User : {"ar":"","ku":"یوزەر","en":"User"},
	cashTable : {"ar":"","ku":"خشتەی سندوق","en":"Cash Table"},
	transferMoney : {"ar":"","ku":"پارە گواستن","en":"Transfer Money"},
	cashBalance : {"ar":"","ku":"مەوجوودی سندوق","en":"Cash Balance"},
	transferToAccount : {"ar":"","ku":"ناردن بۆ حیسابی","en":"Transfer To Account"},
	Dollar : {"ar":"","ku":"دۆلار","en":"Dollar"},
	cashAmount : {"ar":"","ku":"مەوجوودی","en":"Cash Amount"},
	amountTrasfer : {"ar":"","ku":"بڕی پارە","en":"Amount Trasfer"},
	AmountToSend : {"ar":"","ku":"بڕی پارە بۆ ناردن","en":"Amount To Send"},
	This_Amount_Not_Exist_By_Cash : {"ar":"","ku":"ئەم برە پارەیە بە نەقد نێت","en":"This Amount Not Exist By Cash"},
	Mobiles : {"ar":"","ku":"موبایلەکان","en":"Mobiles"},
	Snapshot : {"ar":"","ku":"راپۆرتی خێرا","en":"Snapshot"},
	FirstDate : {"ar":"","ku":"یەکەم رۆژ","en":"FirstDate"},
	LastDate : {"ar":"","ku":"کۆتا رۆژ","en":"LastDate"},
	AllDepartment : {"ar":"","ku":"هەموو بەشەکان","en":"AllDepartment"},
	AllTransaction : {"ar":"","ku":"هەموو مامەڵەکان","en":"AllTransaction"},
	Balance : {"ar":"","ku":"بالانس","en":"Balance"},
	Resid : {"ar":"","ku":"رسید","en":"Resid"},
	Payables : {"ar":"","ku":"ئەبێ بدرێ","en":"Payables"},
	Receivable : {"ar":"","ku":"ئەبێ وەرگیرێ","en":"Receivable"},
	Store : {"ar":"","ku":"گەنجینە","en":"Store"},
	Equipment : {"ar":"","ku":"ئەجیزە","en":"Equipment"},
	DayExpense : {"ar":"","ku":"خەرجی رۆژانە","en":"DayExpense"},
	You_Must_Delete_Transaction : {"ar":"","ku":"سەراتا ئەبێ حیساباتی تایبەت بە ئەم وەسلە سیفر کرێت","en":"You Must Delete Transaction"},
	Alert : {"ar":"","ku":"ئاگادار بە","en":"Alert"},
	send : {"ar":"","ku":"ناردن","en":"Send"},
	outdepp_pieceTable : {"ar":"","ku":"خشتەی پسولەی فرۆش","en":"Outdepp Piece Table"},
	total : {"ar":"","ku":"کۆ","en":"total"},
	AreYouSureToDelete : {"ar":"","ku":"دلنیای بۆ سرینەوە؟","en":"Are You Sure To Delete?"},
	Add : {"ar":"","ku":"زیاد کردن","en":"Add"},
	Edit : {"ar":"","ku":"گۆرانکاری","en":"Edit"},
	Delete : {"ar":"","ku":"سرینەوە","en":"Delete"},
	balance : {"ar":"","ku":"بالانس","en":"Balance"},
	AddTransaction : {"ar":"","ku":"زیاد کردنی مامەڵە","en":"Add Transaction"},
	From : {"ar":"","ku":"کەمی کەوە","en":"From"},
	AccountType : {"ar":"","ku":"جۆری حیساب","en":"Account Type"},
	To : {"ar":"","ku":"بینێرە بۆ","en":"To"},
	Description : {"ar":"","ku":"شەرح","en":"Description"},
	inDollar : {"ar":"","ku":"بە دۆلار","en":"In Dollar"},
	dollar_rateTable : {"ar":"","ku":"خشتەی نرخی دۆلار","en":"Dollar Rate Table"},
	rate : {"ar":"","ku":"نرخ","en":"Rate"},
	Dollar_rate : {"ar":"","ku":"نرخی دۆلار","en":"Dollar Rate"},
	It_is_not_today : {"ar":"","ku":"تەنیا ئەبێ ئەمرۆ بێ","en":"It is not today"},
	view : {"ar":"","ku":"بینین","en":"View"},
	SaveCustomer : {"ar":"","ku":"سەیڤ کردنی کڕیار","en":"Save Customer"},
	Print : {"ar":"","ku":"پرینت","en":"Print"},
	Dinar : {"ar":"","ku":"دینار","en":"Dinar"},
	Send : {"ar":"","ku":"ناردن","en":"Send"},
	indepp_mobile_edit : {"ar":"","ku":"گۆرانکاری لە پسولەی داخل کردنی موبایل","en":"Indepp Mobile Edit"},
	permTable : {"ar":"","ku":"خشتەی ئیجازەکان","en":"Permission Table"},
	fund : {"ar":"","ku":"سندوق","en":"Fund"},
	customer : {"ar":"","ku":"کڕیار","en":"customer"},
	store_model : {"ar":"","ku":"گەنجینە مۆدێل","en":"store model"},
	store_piece : {"ar":"","ku":"گەنجینە قەتعە","en":"store piece"},
	in_repair : {"ar":"","ku":"لە چاک کردنەوە","en":"in repair"},
	in_model : {"ar":"","ku":"لە مۆدێل","en":"in model"},
	in_piece : {"ar":"","ku":"لە قەتعە","en":"in piece"},
	college : {"ar":"","ku":"کۆلێج","en":"college"},
	new_old : {"ar":"","ku":"نوێ کۆن","en":"new old"},
	backup : {"ar":"","ku":"بەکئۆپ","en":"backup"},
	user_deppTable : {"ar":"","ku":"خشتەی بەش بۆ بەکارهێنەر","en":"User Depp Table"},
	edit_user_depp : {"ar":"","ku":"گۆرانکاری لە بەش بۆ بەکارهێنار","en":"Edit User Depp"},
	delete_user_depp : {"ar":"","ku":"سرینەوەی بەش بۆ بەکارهێنار","en":"Delete User Depp"},
	add_user_depp : {"ar":"","ku":"زیادکردنی بەش بۆ بەکارهێنار","en":"Add User Depp"},
	cityTable : {"ar":"","ku":"خشتەی شارەکان","en":"City Table"},
	branchTable : {"ar":"","ku":"خشتەی لقەکان","en":"Branch Table"},
	Branch : {"ar":"","ku":"لق","en":"Branch"},
	repair_computer : {"ar":"","ku":"چاک کردنەوەی کۆمپیوتەر","en":"Repair Computer"},
	Depp : {"ar":"","ku":"","en":"Department"},
	depp_catTable : {"ar":"","ku":"خشتەی جۆر بۆ بەش","en":"Department-Category Table"},
	edit_depp_cat : {"ar":"","ku":"گۆرانکاری لە جۆر بۆ بەش","en":"Edit Depp Cat"},
	delete_depp_cat : {"ar":"","ku":"سرینەوەی جۆر بۆ بەش","en":"Delete Depp Cat"},
	add_depp_cat : {"ar":"","ku":"زیادکردنی جۆر بۆ بەش","en":"Add Depp Cat"},
	catTable : {"ar":"","ku":"خشتەی جۆرەکان","en":"Category Table"},
	edit_cat : {"ar":"","ku":"گۆرانکاری جۆر","en":"Edit Category"},
	delete_cat : {"ar":"","ku":"سرینەوەی جۆر","en":"Delete Category"},
	add_cat : {"ar":"","ku":"زیادکردنی جۆر","en":"Add Category"},
	brandTable : {"ar":"","ku":"خشتەی برەندەکان","en":"Brand Table"},
	modelTable : {"ar":"","ku":"خشتەی مۆدێلەکان","en":"Model Table"},
	priceBuy : {"ar":"","ku":"نرخی کەوتوو","en":"Price Buy"},
	storeTable : {"ar":"","ku":"خشتەی گەنجینە","en":"Store Table"},
	PayableExpense : {"ar":"","ku":"خەرجی قەرز","en":"Payable Expense"},
	qty : {"ar":"","ku":"ژمارە","en":"QTY"},
	outdepp_mobile_edit : {"ar":"","ku":"گۆرانکاری لە پسولەی فرۆشتنی مۆبایل","en":"Outdepp Mobile Edit"},
	outdepp_piece : {"ar":"","ku":"پسولەی فرۆش قەتعەکانی مۆبایل","en":"Outdepp Piece"},
	indepp_piece : {"ar":"","ku":"پسولەی کرینی قەتعەکانی موبایل","en":"Indepp Piece"},
	outdepp_mobile_print : {"ar":"","ku":"پسولەی فرۆشی موبایل","en":"Outdepp Mobile Invoice"},
	outdepp_mobileTable : {"ar":"","ku":"خشتەی پسولەی فرۆشتنی موبایل","en":"Outdepp Mobile Table"},
	totalSell : {"ar":"","ku":"کۆی فرۆش - ئەم مانگە","en":"Total Sell (month)"},
	moreInfo : {"ar":"","ku":"زانیاری زیاتر","en":"More Info"},
	countSell : {"ar":"","ku":"عەدەدی فرۆش - ئەم مانگە","en":"Count Sell (month)"},
	newCustomer : {"ar":"","ku":"کریاری نوێ - ئەم مانگە","en":"New Customer (month)"},
	totalBuy : {"ar":"","ku":"کۆی کرین","en":"Total Buy"},
	dailySellChart : {"ar":"","ku":"بەرئاوردی فرۆشی رۆژانە","en":"Daily Sell Chart"},
	GetReport : {"ar":"","ku":"ڕاپۆرت","en":"Get Report"},
	dollarRate : {"ar":"","ku":"نرخی دۆلار","en":"Dollar Rate"},
	balanceSheet : {"ar":"","ku":"بالانسی حیسابات","en":"Balance Sheet"},
	outdepp_mobile_new : {"ar":"","ku":"پسولەی فرۆشی موبایل","en":"Mobile Sell Invoice"},
	totalQty : {"ar":"","ku":"کۆی عەدەد","en":"Total Qty"},
	invoiceSell : {"ar":"","ku":"پسولەی فرۆش","en":"Invoice"},
	Accounter : {"ar":"","ku":"ژمێریار","en":"Accounter"},
	dateForPayThisAmount : {"ar":"","ku":"بەرواری وەرگرتنی پارەی ئەم پسولەیە","en":"Date For Pay This Amount"},
	preBalance : {"ar":"","ku":"قەرزی پێشوو","en":"Previous Balance"},
	newBalance : {"ar":"","ku":"قەرزی نوێ","en":"New Balance"},
	Type : {"ar":"","ku":"جۆر","en":"Type"},
	Creditor : {"ar":"","ku":"قەرزدەر","en":"Creditor"},
	Debtor : {"ar":"","ku":"قەرزدار","en":"Debtor"},
	drawing : {"ar":"","ku":"سەرمایە","en":"Drawing"},
	company : {"ar":"","ku":"کۆمپانیا","en":"Company"},
	balanceTable : {"ar":"","ku":"خشتەی بالانسەکان","en":"Balance Table"},
	viewDetail : {"ar":"","ku":"وردبینی","en":"View Detail"},
	partner : {"ar":"","ku":"وەکیل","en":"Partner"},
	logAndBackup : {"ar":"","ku":"چالاکی و بەکئۆپ","en":"Log And Backup"},
	Log : {"ar":"","ku":"چالاکی","en":"Log"},
	logTable : {"ar":"","ku":"خشتەی چالاکێکان","en":"Logs Table"},
	part : {"ar":"","ku":"بەش","en":"Part"},
	idTable : {"ar":"","ku":"ئایدی خشتە","en":"ID Table"},
	Field : {"ar":"","ku":"فیلد","en":"Field"},
	Before : {"ar":"","ku":"پێشتر","en":"Before"},
	After : {"ar":"","ku":"دوایی","en":"After"},
	table : {"ar":"","ku":"خشتە","en":"table"},
	acc : {"ar":"","ku":"مامەڵە","en":"transaction"},
	indepp : {"ar":"","ku":"پسولەی کرین","en":"invoice in"},
	ordered : {"ar":"","ku":"داواکاری - چاک کردنەوە","en":"ordered"},
	outdepp : {"ar":"","ku":"پسولەی فرۆش","en":"invoice out"},
	repairman : {"ar":"","ku":"چاک کەرەوە","en":"repairman"},
	log : {"ar":"","ku":"چالاکی","en":"log"},
	Filter : {"ar":"","ku":"فیلتەر","en":"Filter"},
	indepp_mobile_new : {"ar":"","ku":"پسولەی کرینی مۆبایل","en":"Buy New Mobiles"},
	indepp_mobileTable : {"ar":"","ku":"خشتەی پسولەی کرینی موبایل","en":"Indepp Mobile Table"},
	accountTotalView : {"ar":"","ku":"گشتی مامەلەکانی حیسابی","en":"Account Total View"},
	deppBalance : {"ar":"","ku":"بلانسی بەش","en":"DBalance"},
	modelName : {"ar":"","ku":"ناوی مۆدێل","en":"Model Name"},
	Accessories : {"ar":"","ku":"ئیکسیسوارات","en":"Accessories"},
	outdepp_accTable : {"ar":"","ku":"خشتەی ئیکسیسوارات","en":"Table Accessories"},
	outdepp_piece_edit : {"ar":"","ku":"گۆرانکاری لە پسولەی فرۆشتنی قەتعەکانی موبایل","en":"Outdepp Piece Invoice Edit"},
	outdepp_acc_edit : {"ar":"","ku":"گۆرانکاری لە پسولەی فرۆشتنی ئیکسیسوارات","en":"Outdepp Accessories Invoice Edit"},
	outdepp_acc : {"ar":"","ku":"پسولەی ئیکسیسوارات","en":"Outdepp Accessories"},
	outdepp_acc_print : {"ar":"","ku":"پسولەی فرۆشی ئیکسیسوارات","en":"Indepp Accessories Invoice"},
	indepp_acc_edit : {"ar":"","ku":"گۆرانکاری لە پسولەی کرینی ئیکسیسوارات","en":"Indepp Accessories Invoice Edit"},
	indepp_acc_print : {"ar":"","ku":"پسولەی کرینی ئیکسیسوارات","en":"Outdepp Accessories Invoice"},
	indepp_acc : {"ar":"","ku":"پسولەی ئیکسیسوارات","en":"Indepp Accessories"},
	indepp_accTable : {"ar":"","ku":"خشتەی کرینی ئیکسیسوارات","en":"Indepp Accessories Table"},
	indepp_acc_new : {"ar":"","ku":"پسولەی کرینی ئیکسیسوارات","en":"Buy New Accessories"},
	outdepp_acc_new : {"ar":"","ku":"پسولەی فرۆشی ئیکسیسوارات","en":"Accessories Sell Invoice"},
	Range : {"ar":"","ku":"مەودا","en":"Range"},
	Range : {"ar":"","ku":"مەودا","en":"Range"},
	rangeTable : {"ar":"","ku":"خشتەی مەوداکان","en":"Range Table"},
	moderate : {"ar":"","ku":"دابین","en":"Moderate"},
	ProductReportInMonth : {"ar":"","ku":"راپۆرتی فرۆشی بەرهەم لە مانگ","en":"Product Report In Month"},
	viewMore : {"ar":"","ku":"بینینی زیاتر","en":"View More"},
	category : {"ar":"","ku":"جۆر","en":"Category"},
	total_qty : {"ar":"","ku":"کۆی عەدەد","en":"Total Qty"},
	total_cost : {"ar":"","ku":"کۆی گشتی فرۆش","en":"Total Cost"},
	total_profit : {"ar":"","ku":"کۆی قازانج","en":"Total Profit"},
	productSellReport : {"ar":"","ku":"راپۆرتی فرۆشی بەرهەم","en":"Product Sell Report"},
	to : {"ar":"","ku":"تا","en":"to"},
	debtsReport : {"ar":"","ku":"راپۆرتی قەرز","en":"Debts Report"},
	Days : {"ar":"","ku":"رۆژ","en":"Days"},
	Toll : {"ar":"","ku":"کرێ","en":"Toll"},
	tollFromAccount : {"ar":"","ku":"کرێ بار لە حیسابی","en":"Toll From Account"},
	indepp_mobile : {"ar":"","ku":"پسولەی کرینی موبایل","en":"Mobile Buy Invoice"},
	price_buy : {"ar":"","ku":"نرخی کەوتوو","en":"price_buy"},
	Jard : {"ar":"","ku":"جەرد","en":"Jard"},
	debtsReportSimple : {"ar":"","ku":"راپۆرتی قەرزی سادە","en":"Simple Debts Report"},
	Day : {"ar":"","ku":"رۆژ","en":"Day"},
	Paid : {"ar":"","ku":"پارەی دراو","en":"Paid"},
	days : {"ar":"","ku":"رۆژ","en":"days"},
	darham_rate : {"ar":"","ku":"درهم","en":"Darham Rate"},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""},
	m : {"ar":"","ku":"","en":""}
}

